### ISSUE TITLE
Clear cache?

### ISSUE THREAD

**Issue by Altreus** [lizmat/ObjectCache#1]
Another lizmat module that does exactly what I was trying to figure out how to do!

The documentation does not suggest a way to remove an object from cache. I was going to use it to avoid unnecessarily fetching an API object I already have, but I would like to be able to drop my cached data so I can re-fetch it.

**Comment by lizmat** [comment]
Sorry for the delay, I somehow missed the notices of these issues.  Probably because I was working on my slides for the GPaRW.

Anyways, https://github.com/lizmat/ObjectCache/commit/b8844124637c43461df6d46572f14e1173fd0ece implements a `!EVICT` private method, which you can call from a method in your class.  This is now on its way to CPAN and should become available in a few hours.
